global using LetsShopping.Domain.Exceptions.Orders;
global using LetsShopping.Domain.Models.Addresses;
global using LetsShopping.Domain.Models.Orders;
global using LetsShopping.Domain.Models.Products;
global using LetsShopping.Service.Interfaces.Order;
global using LetsShopping.Service.Interfaces.Users;
global using LetsShopping.DataAccess.Repositories.CardsRepositories;
global using LetsShopping.DataAccess.Repositories.CartsRepositories;
global using LetsShopping.DataAccess.Repositories.UserRepository;