global using System.Data.SqlClient;
global using LetsShopping.Domain.Models.Orders;
global using LetsShopping.Service.Dtos.OrdersDtos;
global using LetsShopping.Service.Dtos.Price;
global using Dapper;
global using LetsShopping.Domain.Dtos.AddressDtos;
global using LetsShopping.Domain.Models.Addresses;
global using LetsShopping.Domain.Enums;
global using LetsShopping.Domain.Models.Price;
