global using LetsShopping.DataAccess.Repositories.CartsRepositories;
global using LetsShopping.DataAccess.Repositories.OrderRepositories;
global using LetsShopping.DataAccess.Repositories.UserRepository;
global using LetsShopping.Domain.Dtos.CartsDtos;
global using LetsShopping.Domain.Dtos.OrdersDtos;
global using LetsShopping.Service.Interfaces.Order;
global using LetsShopping.Service.Interfaces.Users;
global using LetsShopping.Service.Services.Order;
global using Microsoft.AspNetCore.Mvc;
